In [1]:
from midi_processing import *
from keys_normalization import *

In [2]:
pcs = MidiProcessor('TS1')

In [3]:
test_midi = '../../test_midi/ls.mid'
track = -3

In [4]:
midi_obj = pcs.load_midi(test_midi)

In [5]:
pos_info = pcs.collect_pos_info(midi_obj, tracks=track)

In [6]:
notes = get_notes_from_pos_info(pos_info)

In [7]:
len(notes)

693

In [8]:
histogram = get_pitch_class_histogram(notes)

In [9]:
histogram

array([0.        , 0.05579131, 0.265111  , 0.00126798, 0.25753888,
       0.        , 0.2346487 , 0.03018621, 0.05579131, 0.05816879,
       0.        , 0.04149581])

In [10]:
import pickle

In [11]:
with open('key_profile.pickle', 'rb') as f:
    key_profile = pickle.load(f)

In [12]:
key_candidate = np.dot(key_profile, histogram)

In [14]:
print(key_profile.shape, histogram.shape, key_candidate.shape)

(24, 12) (12,) (24,)


In [17]:
key_candidate

array([ 0.30500138, -0.30500138,  0.8858814 , -0.29528698,  0.40940558,
        0.22200976, -0.22200976,  0.77429877, -0.71392635,  0.93709161,
       -0.29053204,  0.29306801, -0.29528698,  0.40940558,  0.22200976,
       -0.22200976,  0.77429877, -0.71392635,  0.93709161, -0.29053204,
        0.29306801,  0.30500138, -0.30500138,  0.8858814 ])

In [15]:
key_temp = np.where(key_candidate == max(key_candidate))

In [24]:
key_candidate == max(key_candidate)

array([False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False])

In [25]:
np.where(_)

(array([ 9, 18], dtype=int64),)

In [16]:
key_temp

(array([ 9, 18], dtype=int64),)